name: Windows LiteManager
on:
  workflow_dispatch:
jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/1m_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Downloads.bat" -Wait

      - name: Connect to Lite Manager
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c show.bat" -Wait

      - name: Time Counter
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c loop.bat" -Wait
